#%RAML 1.0

title: 钛旗云管理系统接口文档
version: 1.0.0
baseUri: http://172.23.43.16:32409


/kong/consumers/:
  displayName: 用户列表
  get:
    description: 获取所有用户列表
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      order_by:
        required: false
        enum: ['id', 'username', 'is_active', '-id', '-username', '-is_active']
      is_active:
        required: false
        type: boolean
      keyword:
        required: false
        description: 根据用户名、机构名称、机构代码、联系人等字段综合筛选
      service_name:
        required: false
      username:
        required: false
      username__icontains:
        required: false
      org_name:
        required: false
      org_name__icontains:
        required: false
      org_code:
        required: false
      org_code__icontains:
        required: false
      supplier_service_apinum:
        required: false
        description: 根据第三方API的编号筛选

    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "count": 1,
                  "next": null,
                  "previous": null,
                  "results": [
                      {
                          "id": 1,
                          "username": "test1",
                          "key": "",
                          "is_active": false,
                          "org_name": "测试机构",
                          "org_en": "test org",
                          "org_code": "88229344",
                          "org_address": "",
                          "server_ip": "10.25.45.2",
                          "link_man": "张三",
                          "link_phone": "13111114454",
                          "link_email": "ttt@163.com",
                          "service_title": "车辆信息查询",
                          "service_name": "car_api",
                          "department": "xxx",
                          "project": "yyy",
                          "created_at": "2019-07-03T13:56:45.908857+08:00"
                      }
                  ]
              }

  post:
    description: 创建新用户
    body:
      application/json:
        properties:
          org_name:
          org_en:
          org_code:
          service_name:
            description: '使用的服务英文代码，要求与 kong 的 service name 一致'
          org_address:
            required: false
          server_ip:
            required: false
          link_man:
            required: false
          link_phone:
            required: false
          link_email:
            required: false
          department:
            required: false
          project:
            required: false
    responses:
      201:
        body:
          application/json:
            example: |
              {
                  "id": 2,
                  "username": "mt88229344683",
                  "key": "",
                  "is_active": false,
                  "org_name": "测试机构",
                  "org_en": "my test",
                  "org_code": "88229344",
                  "org_address": "",
                  "server_ip": "10.25.45.2",
                  "link_man": "张三",
                  "link_phone": "13111114454",
                  "link_email": "ttt@163.com",
                  "service_title": "车辆信息查询",
                  "service_name": "car_api",
                  "created_at": "2019-07-03T17:02:55.111713+08:00"
              }

/kong/consumers/{id}/:
  displayName: 用户详情
  get:
    description: 获取目标用户信息
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "id": 1,
                  "username": "test1",
                  "key": "",
                  "is_active": false,
                  "org_name": "测试机构",
                  "org_en": "",
                  "org_code": "88229344",
                  "org_address": "",
                  "server_ip": "10.25.45.2",
                  "link_man": "张三",
                  "link_phone": "13111114454",
                  "link_email": "ttt@163.com",
                  "service_title": "车辆信息查询",
                  "service_name": "car_api",
                  "created_at": "2019-07-03T13:56:45.908857+08:00"
              }
  put:
    description: 修改用户信息
    body:
      application/json:
        properties:
          org_name:
          org_en:
          org_code:
          org_address:
            required: false
          server_ip:
            required: false
          link_man:
            required: false
          link_phone:
            required: false
          link_email:
            required: false
          department:
            required: false
          project:
            required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "id": 1,
                  "username": "test1",
                  "key": "",
                  "is_active": false,
                  "org_name": "测试机构",
                  "org_en": "",
                  "org_code": "88229344",
                  "org_address": "",
                  "server_ip": "10.25.45.2",
                  "link_man": "张三",
                  "link_phone": "13111114454",
                  "link_email": "ttt@163.com",
                  "service_title": "车辆信息查询",
                  "service_name": "car_api",
                  "created_at": "2019-07-03T13:56:45.908857+08:00"
              }
  patch:
    description: 修改部分用户信息 (参考 PUT 方法)
  delete:
    description: 删除用户
    responses:
      204:

/kong/consumers/{id}/set_key/:
  displayName: 设置随机用户秘钥
  post:
    description: 设置随机用户秘钥
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "id": 1,
                  "username": "mt88229344683",
                  "key": "b6ad1e32a63a4eac",
                  "is_active": true,
                  "org_name": "测试机构",
                  "org_en": "my test",
                  "org_code": "88229344",
                  "org_address": "",
                  "server_ip": "10.25.45.2",
                  "link_man": "张三",
                  "link_phone": "13111114454",
                  "link_email": "aaa@163.com",
                  "service_title": "车辆信息查询",
                  "service_name": "car_api",
                  "created_at": "2019-07-03T17:02:55.111713+08:00"
              }


/kong/services/:
  displayName: 服务列表
  get:
    description: 获取所有服务列表
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      order_by:
        required: false
        enum: ['id', 'name', '-id', '-name']
      name:
        required: false
      name__icontains:
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "count": 1,
                  "next": null,
                  "previous": null,
                  "results": [
                      {
                          "id": 1,
                          "name": "test-api",                          // 服务名称 (英文代码)
                          "title": "测试接口",                         // 中文名称
                          "description": "描述描述描述"                // 描述介绍
                          "available": true,                           // 是否可用
                          "url": "http://test.com:80",                 // 服务地址
                          "api_url": "http://rancher.ttt.com/xxx",     // 监控接口地址
                          "consumer_count": 231,                       // 服务用户数
                          "today_called_count": 4396,                  // 今日被调用次数
                          "health": "健康",                            // 健康情况
                          "cpu_usage": 28.8,                           // CPU 占用
                          "memory_usage": 201.5,                       // 内存占用
                          "network_io": [50.5, 62.9],                  // 网络I/O
                          "network_packet": [3.2, 0, 0, 2.5, 0, 0],    // 网络数据包
                          "creaeted_at": "2019-07-03T17:02:55.111713+08:00"   // 服务注册时间
                      }
                  ]
              }

/kong/services/{id}/:
  displayName: 服务详情
  get:
    description: 获取单个服务信息
    responses:
      200:
        body:
          application/json:
            example: |
              {
                // 参考服务列表数据
              }
  patch:
    description: 修改服务信息
    body:
      application/json:
        properties:
          title:
            required: false
          description:
            required: false
          api_url:
            required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  // 参考服务详情数据
              }

/kong/services/{id}/events/:
  displayName: 服务事件日志
  get:
    description: 获取服务事件日志
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      created_at__gte:
        required: false
        type: datetime
        description: 起始时间
      created_at__lte:
        required: false
        type: datetime
        description: 终止时间
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "count": 3,
                  "next": null,
                  "previous": null,
                  "results": [
                      {
                          "id": 1,
                          "created_at": "2019-07-03T17:02:55.111713+08:00", // 时间
                          "event": "服务注册",                              // 服务分类
                          "action": "注册",                                 // 操作
                          "description": "在系统注册服"                     // 描述
                      },
                      {
                          "id": 3,
                          "created_at": "2019-07-03T17:02:55.111713+08:00", // 时间
                          "event": "服务报错",                              // 服务分类
                          "action": "报错",                                 // 操作
                          "description": "出错信息"                         // 描述
                          "confirm"
                      },
                      {
                          "id": 6,
                          "created_at": "2019-07-03T17:02:55.111713+08:00", // 时间
                          "event": "服务升级",                              // 服务分类
                          "action": "升级",                                 // 操作
                          "description": "V3.01，添加xxx功能"               // 描述
                      }
                  ]
              }


/kong/throughput/:
  displayName: 服务吞吐量
  get:
    description: 获取服务吞吐量
    queryParameters:
      begin:
        required: false
        type: datetime
        description: 默认半小时前
      end:
        required: false
        type: datetime
        description: 默认当前时间
      service_name:
        required: false
      username:
        required: false
      interval:
        required: false
        type: integer
        description: 采样间隔（秒），一般不用传，服务端会分配合适的值
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "interval": 60,
                "buckets": [
                    {
                        "time_string": "2019-07-18T15:23:00+08:00",
                        "time": 1563434580,
                        "count": 28,     // 采样时间段的请求总数
                        "qps": 0.47      // 每秒吞吐量数值
                    },
                    {
                        "time_string": "2019-07-18T07:24:00Z",
                        "time": 1563434640,
                        "count": 23,
                        "qps": 0.38
                    }
                ]
              }


/kong/records/:
  displayName: 服务调用日志
  get:
    description: 获取服务调用日志
    queryParameters:
      begin:
        required: false
        type: datetime
        description: 默认半小时前
      end:
        required: false
        type: datetime
        description: 默认当前时间
      service_name:
        required: false
      username:
        required: false
      success:
        required: false
        type: boolean
      size:
        required: false
        type: integer
        default: 500
        description: 最大返回的记录条数（一般情况下不要传，使用默认的500）
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "total": 504,
                  "service_name": null,
                  "username": null,
                  "begin": "2019-07-19T16:37:27.374977+08:00",
                  "end": "2019-07-19T17:07:27.374996+08:00",
                  "hits": [
                      {
                          "timestamp": "2019-07-19T08:37:27.765Z",
                          "kong_request_id": "bcae1f27-bec0-49b7-a057-96392006612f#62061",
                          "service_name": "press-test",
                          "username": "hjp",
                          "real_ip": "172.23.43.15",
                          "request_url": "http://press.kongtest.com/v1/car/match",
                          "request_method": "POST",
                          "response_status": "200",
                          "started_at": "1563525445548",
                          "finished_at": "1563525446063"
                      }
                  ]
              }

/alerts/alerts/:
  displayName: 告警记录列表
  get:
    description: 获取告警记录列表
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      order_by:
        required: false
        enum: ['id', 'status', '-id', '-status']
      code:
        required: false
      status:
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "count": 3,
                  "next": null,
                  "previous": null,
                  "results": [
                      {
                          "id": 3,
                          "code": "E00010000000d00000003",
                          "component_id": 197,
                          "component_code": "C00010000000d0000",
                          "level": 1,
                          "value": 0.0,
                          "description": "tqcloud集群 ticache服务 当前已经停止运行，请尽快检查和恢复!",
                          "status": "报警中",
                          "alerted_at": "2019-07-25T20:36:37.325474+08:00",
                          "confirmed_at": null
                      },
                      {
                          "id": 2,
                          "code": "E00010000000d00000002",
                          "component_id": 197,
                          "component_code": "C00010000000d0000",
                          "level": 1,
                          "value": 0.0,
                          "description": "tqcloud集群 ticache服务 当前已经停止运行，请尽快检查和恢复!",
                          "status": "已确认",
                          "alerted_at": "2019-07-25T20:17:04.653225+08:00",
                          "confirmed_at": "2019-07-25T20:20:57.614862+08:00"
                      },
                      {
                          "id": 1,
                          "code": "E00010000000d00000001",
                          "component_id": 197,
                          "component_code": "C00010000000d0000",
                          "level": 1,
                          "value": 0.0,
                          "description": "tqcloud集群 ticache服务 当前已经停止运行，请尽快检查和恢复!",
                          "status": "已确认",
                          "alerted_at": "2019-07-25T20:15:04.579065+08:00",
                          "confirmed_at": "2019-07-25T20:16:12.809212+08:00"
                      }
                  ]
              }


/alerts/alerts/{id}/confirm/:
  displayName: 确认告警
  post:
    description: 确认告警（确认后 此条告警记录状态变为 `已确认`）


/alerts/components/:
  displayName: 告警部件列表
  get:
    description: 获取告警部件列表
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      order_by:
        required: false
        enum: ['id', 'available', 'category', '-id', '-available', '-category']
      code:
        required: false
      name:
        required: false
      cluster_name:
        required: false
      available:
        required: false
      category:
        required: false
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "count": 69,
                "next": "http://172.23.43.15:32409/alerts/components/?page=2",
                "previous": null,
                "results": [
                    {
                        "id": 197,
                        "code": "C00010000003E0000",
                        "api_url": "https://172.23.43.15:2443/v3/project/c-qd6tx:p-9tcpg/workloads/deployment:kong:tiadmin-worker",
                        "category": "workload",
                        "available": true,
                        "cluster_name": "tqcloud",
                        "name": "tiadmin-worker",
                        "description": "",
                        "tags": ""
                    }
                ]
              }

/alerts/components/{id}/:
  displayName: 单个告警部件信息
  get:
    description: 获取单个告警部件信息
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "id": 197,
                  "code": "C00010000003E0000",
                  "api_url": "https://172.23.43.15:2443/v3/project/c-qd6tx:p-9tcpg/workloads/deployment:kong:tiadmin-worker",
                  "category": "workload",
                  "available": true,
                  "cluster_name": "tqcloud",
                  "name": "tiadmin-worker",
                  "description": "",
                  "tags": ""
              }

