#%RAML 1.0

title: XXX 接口文档
version: 2.0.1
baseUri: http://xxx.test.com

documentation:

  - title: 通用返回格式
    content: |
      ```
      code: 返回码
      msg: 请求结果描述,成功为SUCCESS，失败会描述失败原因
      data: 返回的主体数据
      ```

  - title: 错误码
    content: |
      | code     | 内部编码                 | 描述          |
      |----------|--------------------------|---------------|
      | 0        | SUCCESS                  | 成功          |
      | -1       | UNKNOW_ERROR             | 未知错误      |
      | 10001    | UNAUTHORIZED_ERROR       | 用户未认证    |
      | 10002    | AUTH_ERROR               | 认证失败      |
      | 10003    | TOKEN_ERROR              | token认证失败 |
      | 20001    | PARAM_ERROR | 参数错误    |


securitySchemes:
  auth_login:
    description: |
      可通过以下途径之一，实现用户身份鉴定
      1. 通过 `/user/login` 登录接口获取 `jwt token`
      2. Header 中添加 `Authorization` 设定为 `jwt xxxxx`
    type: x-custom
    describedBy:
      headers:
        Authorization:
          required: true

/user/login:
  displayName: 用户登录
  post:
    description: 用户登录
    body:
      application/json:
        properties:
          username:
            required: true
            type: string
          password:
            required: true
            type: string
        example: |
          {
            "username": "zhang3",
            "password": "pass"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "Success",
                "data": {
                  "jwt": "xxxxxxx",
                  "username": "zhang3",
                  "org_name": "xxx1",
                  "org_code": "yyy2",
                  "linkman": "li4",
                  "phone": "13112345678",
                  "role": 1,
                  "role_des": "使用者"
                }
              }


/user/logout:
  displayName: 用户登出
  post:
    description: 用户登出
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "Success"
              }

/user/info:
  displayName: 用户信息
  securedBy: auth_login
  get:
    description: 获取当前登录用户的信息
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "Success",
                "data": {
                  "username": "zhang3",
                  "org_name": "xxx1",
                  "org_code": "yyy2",
                  "linkman": "li4",
                  "phone": "13112345678",
                  "role": 1,
                  "role_des": "使用者"
                }
              }
  patch:
    description: 修改个人信息
    body:
      application/json:
        properties:
          password:
            required: false
            type: string
          org_name:
            required: false
            type: string
          org_code:
            required: false
            type: string
          linkman:
            required: false
            type: string
          phone:
            required: false
            type: string
        example: |
          {
            "password": "pass",
            "org_name": "xxx1",
            "org_code": "yyy2",
            "linkman": "li4",
            "phone": "13112345678"
          }
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "Success",
                "data": {
                  "username": "zhang3",
                  "org_name": "xxx1",
                  "org_code": "yyy2",
                  "linkman": "li4",
                  "phone": "13112345678",
                  "role": 1,
                  "role_des": "使用者"
                }
              }


/mlabels/tasks/create:
  displayName: 创建新任务
  post:
    description: 创建新任务
    securedBy: auth_login
    body:
      multipart/form-data:
        properties:
          file:
            description: 上传待匹配的文件，为多行文本
            required: true
            type: file
          is_distinct:
            description: 是否去重，1去重/0不去重
            required: false
            type: integer
            default: 1
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "code": 0,
                "msg": "Success"
              }


/mlabels/tasks:
  displayName: 获取任务列表
  securedBy: auth_login
  get:
    description: 获取任务列表
    queryParameters:
      page:
        required: false
        type: integer
      page_size:
        required: false
        type: integer
      name:
        required: false
        type: string
      state:
        required: false
        type: string
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "code": 0,
                  "msg": "Success",
                  "data": {
                      "page": 1,
                      "page_size": 20,
                      "tasks": [
                          {
                              "id": 2,
                              "create_time": "2019-06-13T11:06:01.757",
                              "update_time": "2019-06-13T11:06:03.829",
                              "name": "test.txt",
                              "is_distinct": true,
                              "state": 2,
                              "state_des": "匹配完成",
                              "progress": 100,
                              "download_url": "http://172.23.43.15:30748/mlabels/tasks/1/download"
                          }
                      ]
                  }
              }

  /{task_id}/cancel:
    put:
      description: 取消任务
      securedBy: auth_login
      body:
        application/json:
          properties:
            reason:
              description: 取消原因
              required: true
              example: 超时自动取消
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "status": "canceled"
                }

